// <auto-generated />
using System;
using FarmManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FarmManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251102181535_AddBreedRegistryAndMixedBreedSupport")]
    partial class AddBreedRegistryAndMixedBreedSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FarmManagement.Domain.Entities.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("BirthWeightKg")
                        .HasColumnType("numeric");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BreedComposition")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CurrentLocation")
                        .HasColumnType("text");

                    b.Property<int?>("DamId")
                        .HasColumnType("integer");

                    b.Property<string>("ElectronicId")
                        .HasColumnType("text");

                    b.Property<bool>("IsPurebred")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastBreedingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastCalvingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastHeatDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastPalpationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextExpectedCalvingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("text");

                    b.Property<string>("RegistryOrganization")
                        .HasColumnType("text");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<int?>("SireId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TagId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("WeaningDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("WeaningWeightKg")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DamId");

                    b.HasIndex("ElectronicId")
                        .IsUnique();

                    b.HasIndex("SireId");

                    b.HasIndex("TagId")
                        .IsUnique();

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("FarmManagement.Domain.Entities.BirthRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CalfBirthWeightKg")
                        .HasColumnType("numeric");

                    b.Property<int?>("CalfId")
                        .HasColumnType("integer");

                    b.Property<int>("CalfSex")
                        .HasColumnType("integer");

                    b.Property<int>("CalfStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CalvingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CalvingEase")
                        .HasColumnType("integer");

                    b.Property<int>("DamId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CalfId");

                    b.HasIndex("DamId");

                    b.ToTable("BirthRecords");
                });

            modelBuilder.Entity("FarmManagement.Domain.Entities.BreedingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<int?>("BreedingMethod")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpectedCalvingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("PregnancyStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("SireId")
                        .HasColumnType("integer");

                    b.Property<string>("TechnicianName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SireId");

                    b.HasIndex("AnimalId", "EventDate");

                    b.ToTable("BreedingRecords");
                });

            modelBuilder.Entity("FarmManagement.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("FarmManagement.Domain.Entities.HealthRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdministeredBy")
                        .HasColumnType("text");

                    b.Property<int>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("text");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("Medication")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextDueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Treatment")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId", "EventDate");

                    b.ToTable("HealthRecords");
                });

            modelBuilder.Entity("FarmManagement.Domain.Entities.WeightRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MeasurementDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MeasurementType")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId", "MeasurementDate");

                    b.ToTable("WeightRecords");
                });

            modelBuilder.Entity("FarmManagement.Domain.Entities.Animal", b =>
                {
                    b.HasOne("FarmManagement.Domain.Entities.Animal", "Dam")
                        .WithMany()
                        .HasForeignKey("DamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FarmManagement.Domain.Entities.Animal", "Sire")
                        .WithMany()
                        .HasForeignKey("SireId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Dam");

                    b.Navigation("Sire");
                });

            modelBuilder.Entity("FarmManagement.Domain.Entities.BirthRecord", b =>
                {
                    b.HasOne("FarmManagement.Domain.Entities.Animal", "Calf")
                        .WithMany()
                        .HasForeignKey("CalfId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FarmManagement.Domain.Entities.Animal", "Dam")
                        .WithMany("BirthRecordsAsMother")
                        .HasForeignKey("DamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Calf");

                    b.Navigation("Dam");
                });

            modelBuilder.Entity("FarmManagement.Domain.Entities.BreedingRecord", b =>
                {
                    b.HasOne("FarmManagement.Domain.Entities.Animal", "Animal")
                        .WithMany("BreedingRecords")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmManagement.Domain.Entities.Animal", "Sire")
                        .WithMany()
                        .HasForeignKey("SireId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Animal");

                    b.Navigation("Sire");
                });

            modelBuilder.Entity("FarmManagement.Domain.Entities.HealthRecord", b =>
                {
                    b.HasOne("FarmManagement.Domain.Entities.Animal", "Animal")
                        .WithMany("HealthRecords")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("FarmManagement.Domain.Entities.WeightRecord", b =>
                {
                    b.HasOne("FarmManagement.Domain.Entities.Animal", "Animal")
                        .WithMany("WeightRecords")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("FarmManagement.Domain.Entities.Animal", b =>
                {
                    b.Navigation("BirthRecordsAsMother");

                    b.Navigation("BreedingRecords");

                    b.Navigation("HealthRecords");

                    b.Navigation("WeightRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
